apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app-qa
  namespace: qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
        - name: my-web-app
          image: sandeep199008/my-web-app:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: my-web-app-config
            - secretRef:
                name: my-web-app-secret
